baseURL: http://castounclassifiedinformation.com/
languageCode: en-us
title: Sev 1 Casto
theme: hugo-profile

Paginate: 3

markup:
  goldmark:
    renderer:
      unsafe: true

params:
  title: "CUI"
  description: Sev 1 Casto Griefing
  # staticPath: ""  # The path to serve the static files from
  favicon: "/images/eating.jpeg"

  theme:
    disableThemeToggle: false
    # defaultTheme: "light" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  # navbar:
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: ""
    title: "CUI"
    subtitle: "Casto Unclassified Information"
    content: "Are you up to date on your DISA trainings?  Have you passed your Security+?  Do you have a CISSP/CISM/CISA/CCSP/GSEC?  If you answered yes to any of these questions, blame Casto while there's still time."
    image: /images/casto_cac.jpg
    #button:
      #enable: true
      #name: "Resume"
      #url: "#"
    #socialLinks:
      #fontAwesomeIcons:
        #- icon: fab fa-github
          #url: https://example.com
        #- icon: fab fa-twitter
          #url: https://example.com
      #customIcons:
        #- icon: /fav.png
          #url: "https://example.com"

  # About
  about:
    enable: true
    title: "About Casto"
    image: "/images/kill-me-cropped.png"
    content: |-
      Casto has been with GCDS for 16(!) years.  He joined in December 2005, 2 months after Ovechkin joined the Capitals, and 2 years before the first iPhone was released.  In all that time the caps have won the cup once (time will tell if that's a correlation).
    skills:
      enable: true
      title: "Here are some declassified facts about Casto:"
      items:
        - "Definitely thinks puns are the highest form of humor.  Try him!"
        - "Slightly better at staying with GCDS than Underhill, Bonci, and Bailey"
        - "Self declared 'Lord Mayor of Squirrellytown'"
        - "p4 commit hilarity strongly correlated with stress level"
        - "Likes pizzas with more than 3 toppings, dammit"
        - "Not as good at GCDSing as dyoon, let's be honest (I mean really, who can compete with that)"
        - "Hasn't won the lottery"

  # Experience
  experience:
    enable: true
    items:
      - job: "Federal Engineering"
        company: "FedEng"
        companyUrl: "/images/usb.pdf"
        date: "2005 - Sometime after"
        info:
          enable: true
          content: I mean who's counting at this point anyway.
        content: |
          GCDS went through many name changes over the years.  Back in the day, USB keys were allowed, but only certain ones.  The always fastidious Casto asked that we post the linked signs near all workstations.
      - job: "Custom Engineering"
        company: "Custom Eng"
        companyUrl: "https://storefront.disa.mil/kinetic/disa/service-catalog#/forms/global-content-delivery-service"
        date: "Sometime after - Sometime later"
        info:
          enable: false
        content: |
          This link is the first hit you get when googling 'DISA GCDS'.  Note how fast the site loads (not akamaized) and the quality of the content!  Order now!  You get a discount if you still have one of those USB keys!  Did Bryan have anything to do with this?  Who's to know.
      - job: "Senior Slackitect"
        info:
          enable: true
          content: 28th in all time posts, 39th in the last 30 days.  I'd say he's going for quality over quantity, but...
        company: "First Slack Post"
        companyUrl: "/images/first_slack_message.webm"
        date: "Jan 2016 - present"
        content: "Casto was the 6th member of our nascent Slack workspace in 2016 and has sent over 38000 messages since then.  One of his first posts is linked above; we can only hope it's a reflection of his time in GCDS.  Back in the driver's seat!"
      - job: "GCDS Repeats"
        company: "Boomerangs"
        companyUrl: "https://gcds.com/us-en/ready-to-wear-men-c"
        date: "0 times"
        info:
          enable: true
          content: "Gotta start somewhere I guess"
        content: |
          Bryan is severely lagging behind Lawler, Willoughby, Oxley, and Erhard on returns to GCDS.  Bailey and Underhill handily beat him on Akamai boomerangs.  Was Casto the reason they kept coming back, or (gasp) the reason they kept leaving?!  Time will tell, but maybe if we're lucky he'll go to the 'other' GCDS instead.

  # Education
  education:
    enable: true
    # index: true
    items:
      - title: "Top p4 commits"
        content: |-
            - "initial checkin" 18 times
            - "initial checkin before I go breaking things" 1 time (seems low?)
            - "ch-ch-ch-changes..." 3 times
            - "dirty cow" 9 times
            - "branching to clean up a dirty cow" 1 time (also seems low...)
            - "storing a copy of dirty cow kernels" 1 time (uhh, too high)
      - title: "Select p4 commits"
        content: |-
          - 14278167: FAKE FAKE FAKE - do not use this
          - 17494154: intentionally broken
          - 17429667: whoops
          - 17272042: Let's try not to install over a nebula host, mmmkay?
          - 18379605: Actually adding the tarball and signature files.  I should not be trusted to do this sometimes.
          - 17257053: Dan stole my address, the filthy animal
          - 13103359: Bailey'd
          - 12651356: dumb tpyo
          - 12756600: It\\'s like I can\\'t stop making typos
          - 12313588: sigh, PEBCAK.
          - 12175949: I remember this being easier            

  # Achievements
  achievements:
    enable: false
    items:
      - title: Google kickstart runner
        content: I solved all problems with optimal solution.
        url: https://example.com
      - title: Facebook Hackathon Winner
        content: Developed a product using Artificial Intelligence.
      - title: Hugo Profile
        content: Developed a theme and getting 1K+ downloads per month.
        url: "https://github.com/gurusabarish/hugo-profile"
      - title: Microsoft Imagine Runner
        content: We are developed a product which can help others.
      - title: Google Summer of Code
        content: Contributed to a open source project.
        url: https://example.com

  # projects
  projects:
    enable: true
    items:
      - title: Larry
        content: If I can’t fire Scott Ripley, at least I can hire Bryan Casto
        image: /images/lgu-oktoberfest.jpeg

      - title: Erin McCarthy
        content: Shouldn’t Experience get a 404?
        image: /images/emccarth.jpeg

      - title: Charles Cavanaugh
        content: Although Bryan and I didn’t work closely together this past year and a half, I did have the pleasure of his interviewing me for this position. He definitely struck me as a person who “knows their stuff,” and we seemed to have a good rapport. I would’ve liked to get to know him better, and it’s sad to see someone of high competence leave our team; but I wish him well in his future endeavors!
        image: /images/ccavanau.jpg

      - title: Zlatan
        content: The duo is back together. We waited and waited and the moment finally came. ”America,” “Bridge Over Troubled Water,” “The Boxer”, “The Sound Of Silence. Simon & Garfunkel's odyssey continues as they share the stage again for the first time since their 2010 sold out….What? Not back together? Different duo? Oh, those two, Larry and Bryan are back together doing some Prolexic gig. Check them out if you get a chance. Solos are amazing!
        image: /images/z.jpeg

      - title: Damien “Fido2 guy” Le
        content: When I was interviewed for Akamai, Bryan asked “explains how the internet works” or something like that. It was a thought-provoking question! As a developer I use the internet and never thought too much about the design or the architect how it is supposed to work. Now been here for some time, I realize that Bryan knows a lot about the internet and everything Akamai related! Best of luck in your new position, Bryan!
        image: /images/damien-selfie.JPG

      - title: Tim
        content: I’ll miss dart wars, free donuts, white boarding sessions in Lincoln and therapy sessions on the couch.  Bryan has always been there, no matter what I needed to discuss.  A kindness that extended well beyond GCDS.  When my dad passed, Bryan was there.  I don’t think he knows how much that still means to me to this day.  Bryan is a class act through and through, despite his contact photo in my phone.  His absence will be felt as much as his presence over the past 17 years.
        image: /images/tdaffron.jpg
        featured:
          name: a typical day
          link: /images/kill-me.jpg

      - title: Dan 'when do you need it by' Falcone
        content: It's a good thing Bryan's leaving - his cube was about to consume mine.  Dibs on the fallout nuke!  
        image: /images/dafalcon.jpg
        featured:
          name: twins
          link: /images/twins.jpeg

      - title: Simon
        content: fine you get the nuke, i call dibs on the cube.  i wanna bury the hatchet anyway
        image: /images/sverasch.jpeg
        featured:
          name: thisisunsafe
          link: /images/burythehatchet.mov

      - title: Jon Oxley
        content: |
          The first I knew of Bryan was the head engineer guy, the guy who knew everything.  Eventually I learned the title architect, but he was one of the engineering wizards who you rarely saw.  I was ops so I never really talked to him unless something was severely and horribly broken.  One vivid memory I have is during my first installment at Akamai.  Was working in the NOCC and was a bit shocked to see him walk in first thing early in the morning.  He had a box of donuts in his hand.

          His words were of the sort, “Sorry guys, I brought donuts because the internet is about to have a very bad day….”.  It was one of the first big SSL vulnerabilities, I think.
 
          But slowly as I grew in my Akamai experiences, it took a while, but I learned to not be terrified of him walking into the NOCC.  However, certain people you just know, don’t have time to waste.  If there is a list of those people Bryan would be at the top of it.  So, when you see them around, the pulse quickens with thoughts of “what’s about to happen here”?
 
          In my second turn here, my assumption about him being an all-knowing wizard was confirmed as time and time again as he guided me through various security debacles and helped get us through various compliance issues.
 
          Akamai has among all the other things, given me the best string of supervisors I could have ever imagined.  Bryan Casto would be at the top of that list.  I’m not the best with words so I will just say I’ve been blessed to work under him and Bryan I wish you the very best.
        image: /images/joxley.jpeg

      #- title: Hugo Profile V2
        #content: A clean and simple Hugo template for personal portfolio and blog.
        #image: /images/projects/profile2.jpg
        #featured:
          #name: Demo V2
          #link: https://hugo-profile-2.netlify.app
        # badges:
        #   - "Hugo"
        #   - "Bootstrap"
        #   - "Javascript"
        #links:
          #- icon: fab fa-github
            #url: https://github.com/gurusabarish/HugoProfileV2

  #Contact
  contact:
    enable: false
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: gurusabarisha@gmail.com
    btnName: Mail me

  footer:
    recentPosts: false
    socialNetworks:
      github: https://github.com/dafalcon/castounclassifiiedinformation
      linkedin: https://www.linkedin.com/in/rick-astley-605352208/
      #twitter: https://twitter.com
      #instagram: https://instagram.com
      #facebook: https://facebook.com
